export const EXPECTED_CATEGORY_COUNT = 8;
export const EXPECTED_STARTER_ELEMENT_COUNT = 14;
export const EXPECTED_DISCOVERY_ELEMENT_COUNT = 22;
export const EXPECTED_TOTAL_ELEMENT_COUNT = 36;
export const EXPECTED_STARTER_DETAIL_COUNT = 14;
export const EXPECTED_DISCOVERY_DETAIL_COUNT = 0;

export const SEED_MANIFEST = {
  version: 'v1.0',
  counts: {
    categories: EXPECTED_CATEGORY_COUNT,
    starterElements: EXPECTED_STARTER_ELEMENT_COUNT,
    discoveryElements: EXPECTED_DISCOVERY_ELEMENT_COUNT,
    totalElements: EXPECTED_TOTAL_ELEMENT_COUNT,
    starterDetails: EXPECTED_STARTER_DETAIL_COUNT,
    discoveryDetails: EXPECTED_DISCOVERY_DETAIL_COUNT,
  },
};
