export const EXPECTED_CATEGORY_COUNT = 8;
export const EXPECTED_STARTER_ELEMENT_COUNT = 14;
export const EXPECTED_DISCOVERY_ELEMENT_COUNT = 22;
export const EXPECTED_TOTAL_ELEMENT_COUNT = 36;
export const EXPECTED_STARTER_DETAIL_COUNT = 14;
export const EXPECTED_DISCOVERY_DETAIL_BATCH_A_COUNT = 11;
export const EXPECTED_DISCOVERY_DETAIL_BATCH_B_COUNT = 0;
export const EXPECTED_TOTAL_DISCOVERY_DETAIL_COUNT = 11;
export const EXPECTED_TOTAL_DETAIL_COUNT = 25;

export const SEED_MANIFEST = {
  version: 'v1.0',
  counts: {
    categories: EXPECTED_CATEGORY_COUNT,
    starterElements: EXPECTED_STARTER_ELEMENT_COUNT,
    discoveryElements: EXPECTED_DISCOVERY_ELEMENT_COUNT,
    totalElements: EXPECTED_TOTAL_ELEMENT_COUNT,
    starterDetails: EXPECTED_STARTER_DETAIL_COUNT,
    discoveryDetailsBatchA: EXPECTED_DISCOVERY_DETAIL_BATCH_A_COUNT,
    discoveryDetailsBatchB: EXPECTED_DISCOVERY_DETAIL_BATCH_B_COUNT,
    totalDiscoveryDetails: EXPECTED_TOTAL_DISCOVERY_DETAIL_COUNT,
    totalDetails: EXPECTED_TOTAL_DETAIL_COUNT,
  },
};
