"use client";
import { BookOpen, BookOpenCheck, Eye, Pencil, RotateCcw } from "lucide-react";
import { AdminArchiveDialog } from "@/features/admin/components/admin-archive-dialog";
import type { AdminElementSummary, ContentStatusEnum } from "../types/admin-element.type";

type ListProps = { elements: AdminElementSummary[]; isSubmitting: boolean; onEdit: (element: AdminElementSummary) => void; onOpenDetail: (element: AdminElementSummary) => void; onArchive: (elementId: string, name: string) => Promise<boolean>; onReactivate: (elementId: string, name: string) => Promise<boolean> };
const statusStyles: Record<ContentStatusEnum, string> = { ACTIVE: "border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300", PENDING: "border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-300", INACTIVE: "border-stone-500/30 bg-stone-500/10 text-stone-700 dark:text-stone-300", ARCHIVED: "border-red-500/30 bg-red-500/10 text-red-700 dark:text-red-300" };

function StatusBadge({ status }: { status: ContentStatusEnum }) { return <span className={"inline-flex min-h-6 items-center rounded-full border px-2 py-0.5 text-[10px] font-bold " + statusStyles[status]}>{status}</span>; }
function DetailState({ hasDetail }: { hasDetail: boolean }) { const Icon = hasDetail ? BookOpenCheck : BookOpen; return <span className={"inline-flex items-center gap-1 text-xs font-semibold " + (hasDetail ? "text-(--brand-primary)" : "text-muted-foreground")}><Icon className="size-4" aria-hidden="true" />{hasDetail ? "Detail ready" : "Detail missing"}</span>; }
function formatUpdatedAt(value: string): string { const date = new Date(value); if (Number.isNaN(date.getTime())) return "Updated time unavailable"; return "Updated " + date.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" }); }

function ElementActions({ element, isSubmitting, onOpenDetail, onEdit, onArchive, onReactivate }: { element: AdminElementSummary; isSubmitting: boolean; onOpenDetail: () => void; onEdit: () => void; onArchive: () => Promise<boolean>; onReactivate: () => Promise<boolean> }) {
  const canArchive = element.status === "ACTIVE" || element.status === "PENDING";
  return <div className="flex flex-wrap items-center justify-start gap-2 md:justify-end">
    <button id={"inspect-element-" + element.id} type="button" onClick={onOpenDetail} aria-label={"Inspect detail for " + element.name} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-(--border-interactive) px-3 text-xs font-semibold text-(--brand-primary) hover:bg-(--surface-inset) focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--focus-ring)"><Eye className="size-4" aria-hidden="true" />Inspect</button>
    <button id={"edit-element-" + element.id} type="button" onClick={onEdit} aria-label={"Edit " + element.name} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-(--border-subtle) bg-(--surface-inset) px-3 text-xs font-semibold text-foreground hover:bg-(--surface-raised) focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--focus-ring)"><Pencil className="size-4" aria-hidden="true" />Edit</button>
    {canArchive ? <AdminArchiveDialog trigger={<button type="button" disabled={isSubmitting} aria-label={"Archive " + element.name} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-amber-500/30 px-3 text-xs font-semibold text-amber-700 hover:bg-amber-500/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500/50 disabled:opacity-50">Archive</button>} itemName={element.name} description="This changes the Element status to INACTIVE. Its Category, detail, and stored Recipe relationships remain attached; the Element can be reactivated later." isPending={isSubmitting} onConfirm={onArchive} /> : <button type="button" onClick={() => void onReactivate()} disabled={isSubmitting} aria-label={"Reactivate " + element.name} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-(--border-interactive) px-3 text-xs font-semibold text-(--brand-primary) hover:bg-(--surface-inset) focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--focus-ring) disabled:opacity-50"><RotateCcw className="size-4" aria-hidden="true" />Reactivate</button>}
  </div>;
}
function ElementRecord({ element, isSubmitting, onEdit, onOpenDetail, onArchive, onReactivate }: { element: AdminElementSummary; isSubmitting: boolean; onEdit: () => void; onOpenDetail: () => void; onArchive: () => Promise<boolean>; onReactivate: () => Promise<boolean> }) {
  return <article role="listitem" className="grid gap-4 border-b border-(--border-subtle) p-4 last:border-b-0 md:grid-cols-[minmax(0,1.7fr)_minmax(0,1.2fr)_minmax(11rem,1.2fr)_auto] md:items-center">
    <div className="min-w-0 space-y-2"><div className="flex min-w-0 flex-wrap items-center gap-3"><span className="text-xl leading-none" aria-hidden="true">{element.emoji}</span><h3 className="break-words text-sm font-bold text-foreground">{element.name}</h3><StatusBadge status={element.status} /></div><p className="break-words text-xs leading-5 text-muted-foreground"><span className="font-semibold text-(--color-craft-accent)">{element.categoryName}</span><span aria-hidden="true"> · </span>{element.elementType}<span aria-hidden="true"> · </span><span className="font-mono">/{element.slug}</span></p></div>
    <div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground"><span>{element.isStarter ? "Starter Element" : "Standard Element"}</span><DetailState hasDetail={element.hasDiscoveryDetail} /><span>{formatUpdatedAt(element.updatedAt)}</span></div>
    <div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-muted-foreground">Lifecycle changes are in Edit</span></div>
    <ElementActions element={element} isSubmitting={isSubmitting} onOpenDetail={onOpenDetail} onEdit={onEdit} onArchive={onArchive} onReactivate={onReactivate} />
  </article>;
}

export function AdminElementList({ elements, isSubmitting, onEdit, onOpenDetail, onArchive, onReactivate }: ListProps) {
  if (elements.length === 0) return <div className="surface-inset rounded-2xl p-8 text-center"><p className="text-sm font-semibold text-foreground">No Elements found</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Create a master Element to begin building the shared catalogue.</p></div>;
  return <div role="list" aria-label="Admin Elements" className="surface-card overflow-hidden rounded-2xl"><div className="hidden border-b border-(--border-subtle) bg-(--surface-flat) px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground md:grid md:grid-cols-[minmax(0,1.7fr)_minmax(0,1.2fr)_minmax(11rem,1.2fr)_auto] md:gap-4"><span>Element identity</span><span>Content context</span><span>Lifecycle</span><span className="text-right">Actions</span></div>{elements.map((element) => <ElementRecord key={element.id} element={element} isSubmitting={isSubmitting} onEdit={() => onEdit(element)} onOpenDetail={() => onOpenDetail(element)} onArchive={() => onArchive(element.id, element.name)} onReactivate={() => onReactivate(element.id, element.name)} />)}</div>;
}
