import {
  ContentStatus,
  ElementType,
} from '../../../src/database/generated/prisma/client';
import { ElementSeedInput } from './starter-elements';

export const DISCOVERY_ELEMENT_SEED_DATA: ElementSeedInput[] = [
  {
    slug: 'cash-flow',
    name: 'Net Cash Flow',
    categoryName: 'Money Flow',
    elementType: ElementType.CONCEPT,
    emoji: '🔄',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 15,
  },
  {
    slug: 'debt-pressure',
    name: 'Debt Service Burden',
    categoryName: 'Debt & Credit',
    elementType: ElementType.RISK,
    emoji: '⚖️',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 16,
  },
  {
    slug: 'cost-pressure',
    name: 'Living Inflation Pressure',
    categoryName: 'Cost of Living',
    elementType: ElementType.RISK,
    emoji: '📈',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 17,
  },
  {
    slug: 'emergency-resilience',
    name: 'Financial Safety Buffer',
    categoryName: 'Life Events & Risk',
    elementType: ElementType.CONCEPT,
    emoji: '🏰',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 18,
  },
  {
    slug: 'impulse-spending',
    name: 'Unplanned Impulse Purchase',
    categoryName: 'Financial Behavior',
    elementType: ElementType.BEHAVIOR,
    emoji: '🛍️',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 19,
  },
  {
    slug: 'spending-plan',
    name: 'Structured Spending Plan',
    categoryName: 'Planning Tools',
    elementType: ElementType.TOOL,
    emoji: '📐',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 20,
  },
  {
    slug: 'savings-growth',
    name: 'Compounded Savings Growth',
    categoryName: 'Saving & Financial Safety',
    elementType: ElementType.CONCEPT,
    emoji: '🌱',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 21,
  },
  {
    slug: 'debt-trap',
    name: 'Compound Interest Debt Trap',
    categoryName: 'Debt & Credit',
    elementType: ElementType.RISK,
    emoji: '🪤',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 22,
  },
  {
    slug: 'purchasing-power-loss',
    name: 'Real Purchasing Power Erosion',
    categoryName: 'Cost of Living',
    elementType: ElementType.RISK,
    emoji: '📉',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 23,
  },
  {
    slug: 'lifestyle-creep',
    name: 'Lifestyle Inflation Creep',
    categoryName: 'Financial Behavior',
    elementType: ElementType.BEHAVIOR,
    emoji: '🏎️',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 24,
  },
  {
    slug: 'emergency-liquidity',
    name: 'Immediate Liquid Cushion',
    categoryName: 'Saving & Financial Safety',
    elementType: ElementType.TOOL,
    emoji: '💧',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 25,
  },
  {
    slug: 'debt-payoff-strategy',
    name: 'Debt Acceleration Strategy',
    categoryName: 'Planning Tools',
    elementType: ElementType.TOOL,
    emoji: '🎯',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 26,
  },
  {
    slug: 'essential-baseline',
    name: 'Fixed Baseline Expenses',
    categoryName: 'Cost of Living',
    elementType: ElementType.CONCEPT,
    emoji: '⚓',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 27,
  },
  {
    slug: 'discretionary-leakage',
    name: 'Stealth Cash Leakage',
    categoryName: 'Financial Behavior',
    elementType: ElementType.RISK,
    emoji: '💸',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 28,
  },
  {
    slug: 'digital-scam-risk',
    name: 'Digital Fraud Vulnerability',
    categoryName: 'Digital Financial Safety',
    elementType: ElementType.RISK,
    emoji: '🎣',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 29,
  },
  {
    slug: 'financial-stability',
    name: 'Financial Resilience State',
    categoryName: 'Saving & Financial Safety',
    elementType: ElementType.DISCOVERY,
    emoji: '🏆',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 30,
  },
  {
    slug: 'debt-overload',
    name: 'Severe Debt Overload',
    categoryName: 'Debt & Credit',
    elementType: ElementType.RISK,
    emoji: '💥',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 31,
  },
  {
    slug: 'emergency-survival',
    name: 'Shock Survival Capability',
    categoryName: 'Life Events & Risk',
    elementType: ElementType.DISCOVERY,
    emoji: '🧗',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 32,
  },
  {
    slug: 'mindful-spending',
    name: 'Mindful Consumption Behavior',
    categoryName: 'Financial Behavior',
    elementType: ElementType.BEHAVIOR,
    emoji: '🧘',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 33,
  },
  {
    slug: 'budget-optimizing',
    name: 'Dynamic Allocation Strategy',
    categoryName: 'Planning Tools',
    elementType: ElementType.TOOL,
    emoji: '⚡',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 34,
  },
  {
    slug: 'digital-hygiene',
    name: 'Digital Security Shield',
    categoryName: 'Digital Financial Safety',
    elementType: ElementType.TOOL,
    emoji: '🔒',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 35,
  },
  {
    slug: 'financial-freedom-foundation',
    name: 'Financial Independence Core',
    categoryName: 'Planning Tools',
    elementType: ElementType.DISCOVERY,
    emoji: '🌟',
    isStarter: false,
    status: ContentStatus.ACTIVE,
    sortOrder: 36,
  },
];
