import { RealityLevel, SafetyLabel } from '../../../src/database/generated/prisma/client';
import { StarterElementDetailSeedInput } from './starter-element-details';

export type DiscoveryElementDetailSeedInput = StarterElementDetailSeedInput;

export const DISCOVERY_ELEMENT_DETAIL_BATCH_A_SEED_DATA: DiscoveryElementDetailSeedInput[] = [
  {
    elementSlug: 'cash-flow',
    shortDescription: 'Net difference between total cash inflows and total cash outflows over a specific period.',
    realLesson: 'Positive cash flow provides financial margin and flexibility, whereas negative cash flow compresses liquidity and forces reliance on reserves or debt.',
    example: 'A worker earns GBP 2,500 monthly and spends GBP 2,000 on living expenses, generating a positive net cash flow of GBP 500 per month.',
    possibleBenefit: 'Builds liquid reserves, provides financial agility, and supports long-term wealth accumulation.',
    possibleTradeoff: 'Generating cash surplus requires capping immediate living expenses and delaying optional consumption.',
    hiddenRisk: 'Fluctuating income or irregular annual expenses (e.g. insurance, taxes) can temporarily flip positive cash flow into deficit.',
    worksWhen: 'Total cash inflows reliably exceed total mandatory and discretionary spending over defined cycles.',
    becomesDifficultWhen: 'Fixed expenses expand close to net income, or income experiences sudden interruptions.',
    whatChangesOutcome: 'Surplus margin percentage, income stability, expense control, and tracking frequency.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'Financial Education and Core Competencies for Adults',
        organization: 'OECD',
        url: 'https://www.oecd.org/en/topics/sub-issues/financial-education.html',
        jurisdiction: 'GLOBAL',
        sourceType: 'International organisation',
      },
    ],
  },
  {
    elementSlug: 'debt-pressure',
    shortDescription: 'The ongoing financial strain created when fixed debt repayment obligations consume a high portion of monthly income.',
    realLesson: 'High debt service burdens reduce disposable income margin, making households vulnerable to economic or income shocks.',
    example: 'Allocating GBP 1,150 out of GBP 2,500 monthly income (46%) toward mandatory loan repayments, leaving tight cash for living needs.',
    possibleBenefit: 'Servicing debt responsibly maintains credit standing and enables acquisition of essential high-value assets over time.',
    possibleTradeoff: 'Commits a significant percentage of future earnings to fixed repayment contracts, restricting spending flexibility.',
    hiddenRisk: 'Debt service ratios above 40% leave little margin for emergency expenses or sudden income drops.',
    worksWhen: 'Total monthly debt obligations stay well below 30%–40% of net income and interest rates remain low.',
    becomesDifficultWhen: 'Income declines, interest rates rise on variable debt, or unexpected living expenses occur.',
    whatChangesOutcome: 'Debt-to-income ratio, interest rate levels, repayment term lengths, and restructuring options.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.NOT_FINANCIAL_ADVICE,
    sources: [
      {
        title: 'Understanding Credit and Borrowing Costs',
        organization: 'CFPB',
        url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Government regulator',
      },
    ],
  },
  {
    elementSlug: 'cost-pressure',
    shortDescription: 'Cumulative upward pressure on household living expenses caused by rising prices for essential goods and services.',
    realLesson: 'Rising living costs shrink discretionary margins when household income growth does not keep pace with headline price increases.',
    example: 'Monthly utility, food, and transport costs increasing from GBP 1,500 to GBP 1,650 due to general price increases while salary remains unchanged.',
    possibleBenefit: 'Encourages households to review baseline expenses, eliminate waste, and seek income growth opportunities.',
    possibleTradeoff: 'Forces sacrifices in discretionary quality of life or temporary reductions in monthly savings contributions.',
    hiddenRisk: 'Fixed lifestyle patterns delay budget adjustments, causing households to quietly draw down savings buffers.',
    worksWhen: 'Households actively track price changes, adjust spending priorities, and maintain flexible budget allocations.',
    becomesDifficultWhen: 'Inflation spikes rapidly across non-negotiable needs (e.g. food, energy, housing) simultaneously.',
    whatChangesOutcome: 'Rate of price inflation, household spending flexibility, wage growth, and substitute product availability.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'What is Inflation? Measuring Price Stability',
        organization: 'ECB',
        url: 'https://www.ecb.europa.eu/ecb/educational/explainers/tell-me-more/html/what_is_inflation.en.html',
        jurisdiction: 'EUROPEAN_UNION',
        sourceType: 'Central bank',
      },
    ],
  },
  {
    elementSlug: 'emergency-resilience',
    shortDescription: 'A state of financial security achieved when liquid reserves protect households against major unexpected economic shocks.',
    realLesson: 'Financial safety buffers decouple immediate living security from short-term income disruptions or emergency expenses.',
    example: 'Having 6 months of essential living baseline (GBP 9,000) stored in high-yield liquid deposit accounts.',
    possibleBenefit: 'Eliminates acute stress during job transitions, medical emergencies, or home repairs.',
    possibleTradeoff: 'Holding significant cash buffers reduces short-term exposure to higher-yield equity growth assets.',
    hiddenRisk: 'Depleting safety buffers for non-emergency lifestyle purchases leaves households exposed to sudden shocks.',
    worksWhen: 'Reserves match 3–6 months of essential living baseline expenses and are held in liquid accounts.',
    becomesDifficultWhen: 'Prolonged economic recessions exhaust reserves before employment is re-established.',
    whatChangesOutcome: 'Monthly baseline expense size, income volatility, emergency fund discipline, and account yield.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'An Essential Guide to Building an Emergency Fund',
        organization: 'CFPB',
        url: 'https://www.consumerfinance.gov/about-us/blog/an-essential-guide-to-building-an-emergency-fund/',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Government regulator',
      },
    ],
  },
  {
    elementSlug: 'impulse-spending',
    shortDescription: 'Unplanned, emotion-driven purchases that bypass pre-established budget limits.',
    realLesson: 'Impulse spending erodes long-term savings capacity by substituting immediate emotional gratification for planned financial control.',
    example: 'Buying a GBP 200 designer jacket on credit during a flash sale without prior budget allocation.',
    possibleBenefit: 'Provides temporary novelty, pleasure, or immediate lifestyle satisfaction.',
    possibleTradeoff: 'Consumes discretionary surplus that could fund emergency reserves or long-term goals.',
    hiddenRisk: 'Repeated impulse purchases accumulate into substantial credit card debt burdens over time.',
    worksWhen: 'Purchasing friction (e.g. 48-hour cooling-off periods) is intentionally introduced before buying.',
    becomesDifficultWhen: 'Social media marketing and frictionless one-click buying tools trigger compulsive shopping.',
    whatChangesOutcome: 'Emotional self-awareness, budgeting friction rules, credit card usage habits, and goal clarity.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'Spotting and Avoiding Financial Scams',
        organization: 'FTC',
        url: 'https://consumer.ftc.gov/articles/how-to-avoid-a-scam',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Consumer protection agency',
      },
    ],
  },
  {
    elementSlug: 'spending-plan',
    shortDescription: 'A detailed operational framework guiding monthly cash flow toward needs, savings targets, and debt service.',
    realLesson: 'A structured spending plan replaces reactive spending with proactive financial management, aligning daily decisions with long-term goals.',
    example: 'Allocating 50% of net monthly income to essential baseline needs, 20% to savings, and 30% to discretionary wants.',
    possibleBenefit: 'Ensures essential living costs and savings targets are met consistently every month.',
    possibleTradeoff: 'Requires regular tracking effort, time commitment, and personal restraint.',
    hiddenRisk: 'Failing to include irregular annual expenses (e.g. insurance, maintenance) causes budget shortfalls.',
    worksWhen: 'Income and expense figures are realistic, tracked consistently, and updated regularly.',
    becomesDifficultWhen: 'Unexpected price spikes occur or income fluctuates unpredictably without flexible buffers.',
    whatChangesOutcome: 'Tracking frequency, budget realisticness, income stability, and personal discipline.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'Building Blocks of Financial Capability',
        organization: 'CFPB',
        url: 'https://www.consumerfinance.gov/consumer-tools/financial-well-being/',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Government regulator',
      },
    ],
  },
  {
    elementSlug: 'savings-growth',
    shortDescription: 'The gradual accumulation and exponential expansion of capital driven by regular deposits and interest yields.',
    realLesson: 'Compounded savings growth accelerates wealth building by reinvesting annual yields over multi-year horizons.',
    example: 'Depositing GBP 200 monthly into a 4% interest account accumulating over GBP 14,700 after 5 years.',
    possibleBenefit: 'Multiplies personal savings through compound interest yield over extended periods.',
    possibleTradeoff: 'Requires long-term patience, ongoing monthly contributions, and resisting premature withdrawals.',
    hiddenRisk: 'Yields below headline inflation result in real purchasing power decay despite nominal growth.',
    worksWhen: 'Monthly contributions are automated and account returns outpace inflation rates.',
    becomesDifficultWhen: 'Interest rates decline significantly or urgent emergencies force early account liquidation.',
    whatChangesOutcome: 'Monthly deposit size, nominal interest yield, investment horizon, and inflation rate.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'Introduction to Investing and Compound Interest',
        organization: 'Investor.gov',
        url: 'https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Government investor education',
      },
    ],
  },
  {
    elementSlug: 'debt-trap',
    shortDescription: 'A high-risk cycle where compounding debt interest costs exceed monthly repayment capacity, forcing additional borrowing.',
    realLesson: 'Debt traps occur when high interest rates compound faster than principal repayments, trapping borrowers in endless debt cycles.',
    example: 'Taking out high-interest personal loans to cover credit card minimum payments, causing total balance to double in 2 years.',
    possibleBenefit: 'Understanding debt trap mechanics motivates borrowers to eliminate high-APR debt aggressively.',
    possibleTradeoff: 'Escaping a debt trap requires severe reductions in discretionary spending and strict financial austerity.',
    hiddenRisk: 'Ignoring compounding debt costs leads to severe insolvency, legal action, and credit score destruction.',
    worksWhen: 'Borrowers freeze all new credit, seek professional debt assistance, and execute structured avalanche payoff plans.',
    becomesDifficultWhen: 'Interest rates compound at extreme rates while income remains static or declining.',
    whatChangesOutcome: 'Annual percentage rate (APR), principal payoff speed, credit freeze discipline, and debt restructuring terms.',
    realityLevel: RealityLevel.SIMPLIFIED_MODEL,
    safetyLabel: SafetyLabel.NOT_FINANCIAL_ADVICE,
    sources: [
      {
        title: 'Understanding Credit and Borrowing Costs',
        organization: 'CFPB',
        url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Government regulator',
      },
    ],
  },
  {
    elementSlug: 'purchasing-power-loss',
    shortDescription: 'The decay in real goods and services a fixed quantity of money can buy due to inflation.',
    realLesson: 'Inflation steadily diminishes what cash can purchase, requiring capital to grow above inflation to maintain real value.',
    example: 'Holding GBP 10,000 in a zero-interest account during 4% inflation reduces real purchasing value to GBP 9,600 after 1 year.',
    possibleBenefit: 'Highlights the importance of investing capital in inflation-beating growth assets.',
    possibleTradeoff: 'Seeking returns above inflation requires accepting short-term market fluctuation risk.',
    hiddenRisk: 'Keeping all long-term savings in physical cash guarantees steady loss of real purchasing power.',
    worksWhen: 'Capital is allocated to growth assets yielding above the prevailing consumer price inflation rate.',
    becomesDifficultWhen: 'High inflation coincides with depressed market returns and low nominal deposit yields.',
    whatChangesOutcome: 'Inflation rate, portfolio real yield, asset allocation strategy, and investment duration.',
    realityLevel: RealityLevel.SIMPLIFIED_MODEL,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'Inflation: Prices on the Rise',
        organization: 'IMF',
        url: 'https://www.imf.org/en/Publications/fandd/issues/Series/Back-to-Basics/Inflation',
        jurisdiction: 'GLOBAL',
        sourceType: 'International organisation',
      },
    ],
  },
  {
    elementSlug: 'lifestyle-creep',
    shortDescription: 'The automatic expansion of discretionary spending as income rises, preventing savings rate growth.',
    realLesson: 'Lifestyle creep neutralizes salary increases by expanding spending to match new income levels, keeping net savings flat.',
    example: 'Upgrading to a luxury apartment and new car immediately after a salary promotion, keeping monthly savings at zero.',
    possibleBenefit: 'Enables improved personal comfort and lifestyle enjoyment aligned with career growth.',
    possibleTradeoff: 'Commits higher income to fixed spending, preventing acceleration of financial independence.',
    hiddenRisk: 'High fixed costs become severe financial burdens if income later declines unexpectedly.',
    worksWhen: 'Salary increases are systematically directed into savings and investments before upgrading lifestyle spending.',
    becomesDifficultWhen: 'Social status expectations and peer spending pressure drive purchasing decisions.',
    whatChangesOutcome: 'Savings rate automation, personal discipline, spending awareness, and goal clarity.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'Financial Capability and Behavioral Insights',
        organization: 'World Bank',
        url: 'https://www.worldbank.org/en/topic/financialsector/brief/financial-capability',
        jurisdiction: 'GLOBAL',
        sourceType: 'International organisation',
      },
    ],
  },
  {
    elementSlug: 'emergency-liquidity',
    shortDescription: 'Instantly accessible liquid cash reserves available to cover urgent immediate expenses.',
    realLesson: 'Immediate liquid cushions ensure urgent bills can be paid without selling long-term investments or incurring high debt.',
    example: 'Maintaining GBP 3,000 in an instant-access savings account for immediate emergency vehicle repairs.',
    possibleBenefit: 'Provides instant cash access during urgent unforeseen events without transaction delays or penalties.',
    possibleTradeoff: 'Liquid cash yields lower long-term returns than committed growth investment assets.',
    hiddenRisk: 'Mixing emergency liquid reserves with daily checking funds leads to accidental spending on non-emergencies.',
    worksWhen: 'Reserves are kept in separate liquid accounts dedicated strictly to emergency use.',
    becomesDifficultWhen: 'Repeated non-emergency withdrawals drain liquid cushions before real crises occur.',
    whatChangesOutcome: 'Account accessibility, fund segregation, emergency discipline, and reserve size.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'An Essential Guide to Building an Emergency Fund',
        organization: 'CFPB',
        url: 'https://www.consumerfinance.gov/about-us/blog/an-essential-guide-to-building-an-emergency-fund/',
        jurisdiction: 'UNITED_STATES',
        sourceType: 'Government regulator',
      },
    ],
  },
];
