import { RealityLevel, SafetyLabel } from '../../../src/database/generated/prisma/client';
import { StarterElementDetailSeedInput } from './starter-element-details';

export type DiscoveryElementDetailSeedInput = StarterElementDetailSeedInput;

export const DISCOVERY_ELEMENT_DETAIL_BATCH_A_SEED_DATA: DiscoveryElementDetailSeedInput[] = [
  {
    elementSlug: 'cash-flow',
    shortDescription: 'Net difference between total cash inflows and total cash outflows over a specific period.',
    realLesson: 'Positive cash flow provides financial margin and flexibility, whereas negative cash flow compresses liquidity and forces reliance on reserves or debt.',
    example: 'A worker earns THB 30,000 monthly and spends THB 24,000 on living expenses, generating a positive net cash flow of THB 6,000 per month.',
    possibleBenefit: 'Builds liquid reserves, provides financial agility, and supports long-term wealth accumulation.',
    possibleTradeoff: 'Generating cash surplus requires capping immediate living expenses and delaying optional consumption.',
    hiddenRisk: 'Fluctuating income or irregular annual expenses (e.g. insurance, taxes) can temporarily flip positive cash flow into deficit.',
    worksWhen: 'Total cash inflows reliably exceed total mandatory and discretionary spending over defined cycles.',
    becomesDifficultWhen: 'Fixed expenses expand close to net income, or income experiences sudden interruptions.',
    whatChangesOutcome: 'Surplus margin percentage, income stability, expense control, and tracking frequency.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
    ],
  },
  {
    elementSlug: 'debt-pressure',
    shortDescription: 'The ongoing financial strain created when fixed debt repayment obligations consume a high portion of monthly income.',
    realLesson: 'High debt service burdens reduce disposable income margin, making households vulnerable to economic or income shocks.',
    example: 'Allocating THB 14,000 out of THB 30,000 monthly income (46.7%) toward mandatory loan repayments, leaving tight cash for living needs.',
    possibleBenefit: 'Servicing debt responsibly maintains credit standing and enables acquisition of essential high-value assets over time.',
    possibleTradeoff: 'Commits a significant percentage of future earnings to fixed repayment contracts, restricting spending flexibility.',
    hiddenRisk: 'Debt service ratios above 40% leave little margin for emergency expenses or sudden income drops.',
    worksWhen: 'Total monthly debt obligations stay well below 30%–40% of net income and interest rates remain low.',
    becomesDifficultWhen: 'Income declines, interest rates rise on variable debt, or unexpected living expenses occur.',
    whatChangesOutcome: 'Debt-to-income ratio, interest rate levels, repayment term lengths, and restructuring options.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.NOT_FINANCIAL_ADVICE,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
    ],
  },
  {
    elementSlug: 'cost-pressure',
    shortDescription: 'Cumulative upward pressure on household living expenses caused by rising prices for essential goods and services.',
    realLesson: 'Rising living costs shrink discretionary margins when household income growth does not keep pace with headline price increases.',
    example: 'Monthly utility, food, and transport costs increasing from THB 18,000 to THB 19,800 due to general price increases while salary remains unchanged.',
    possibleBenefit: 'Encourages households to review baseline expenses, eliminate waste, and seek income growth opportunities.',
    possibleTradeoff: 'Forces sacrifices in discretionary quality of life or temporary reductions in monthly savings contributions.',
    hiddenRisk: 'Fixed lifestyle patterns delay budget adjustments, causing households to quietly draw down savings buffers.',
    worksWhen: 'Households actively track price changes, adjust spending priorities, and maintain flexible budget allocations.',
    becomesDifficultWhen: 'Inflation spikes rapidly across non-negotiable needs (e.g. food, energy, housing) simultaneously.',
    whatChangesOutcome: 'Rate of price inflation, household spending flexibility, wage growth, and substitute product availability.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'การสำรวจภาวะเศรษฐกิจและสังคมของครัวเรือน (Household Expenditure Survey)',
        organization: 'National Statistical Office Thailand',
        url: 'https://www.nso.go.th',
      },
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
    ],
  },
  {
    elementSlug: 'emergency-resilience',
    shortDescription: 'The structural capacity of a household to absorb negative financial shocks without resorting to high-cost borrowing or asset liquidation.',
    realLesson: 'Combining liquid reserves, insurance coverage, and flexible spending habits creates resilience against unexpected life disruptions.',
    example: 'A household facing an unexpected medical bill of THB 25,000 covers it using liquid savings without missing monthly bills or taking loans.',
    possibleBenefit: 'Provides psychological security, preserves long-term financial plans, and prevents crisis-driven debt accumulation.',
    possibleTradeoff: 'Capital allocated to liquid safety buffers earns modest deposit yields compared to long-term growth investments.',
    hiddenRisk: 'Overestimating resilience based solely on asset net worth while ignoring actual cash liquidity during an immediate crisis.',
    worksWhen: 'Reserves cover 3 to 6 months of essential living costs and are stored in immediately accessible accounts.',
    becomesDifficultWhen: 'Multiple compounding crises occur in rapid succession or prolonged job loss exhausts reserves.',
    whatChangesOutcome: 'Size of liquid buffer, expense flexibility, insurance coverage, and speed of buffer replenishment.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
      {
        title: 'ILO Guidelines on Employment Protection and Social Security',
        organization: 'ILO',
        url: 'https://www.ilo.org',
      },
    ],
  },
  {
    elementSlug: 'impulse-spending',
    shortDescription: 'Unplanned, emotionally-driven spending decisions triggered by immediate desires, social marketing, or promotional psychological cues.',
    realLesson: 'Frequent impulse purchases bypass intentional budget evaluation, quietly eroding surplus cash flow and savings capacity over time.',
    example: 'Buying a THB 4,500 designer item on flash sale without prior planning, reducing planned monthly savings by the same amount.',
    possibleBenefit: 'Understanding emotional spending triggers helps build self-awareness and stronger psychological spending discipline.',
    possibleTradeoff: 'Resisting impulse urges requires emotional energy and enforcing cooling-off rules before making purchases.',
    hiddenRisk: 'Small recurring impulse purchases seem harmless individually but accumulate into substantial annual cash leakage.',
    worksWhen: 'Enforcing spending friction rules (e.g. 48-hour waiting rule, unsubscribing from sales notifications) before buying.',
    becomesDifficultWhen: 'Stress, social peer pressure, or frictionless digital payment apps lower buying resistance.',
    whatChangesOutcome: 'Self-awareness, cooling-off rules, spending friction, budget limits, and social media habits.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'แยกให้ปัง... Needs กับ Wants วางแผนเงินอย่างไรไม่ให้รั่วไหล',
        organization: 'Stock Exchange of Thailand',
        url: 'https://www.setinvestnow.com/th/knowledge/article/117-needs-vs-wants',
      },
    ],
  },
  {
    elementSlug: 'spending-plan',
    shortDescription: 'A systematic operational tool for organizing expected income into structured expense categories, savings targets, and debt payments.',
    realLesson: 'A spending plan translates abstract financial goals into daily actionable boundaries, ensuring surplus allocation before spending.',
    example: 'Dividing monthly net income into fixed needs (50%), discretionary wants (30%), and automated savings/debt payoff (20%).',
    possibleBenefit: 'Directs every unit of currency intentionally, prevents overspending, and systematically builds financial buffers.',
    possibleTradeoff: 'Requires ongoing monitoring effort, expense tracking, and disciplined adherence to spending caps.',
    hiddenRisk: 'Setting overly rigid spending targets without buffer categories can cause budget fatigue and plan abandonment.',
    worksWhen: 'Plans reflect realistic historical spending patterns, include periodic irregular expenses, and are reviewed monthly.',
    becomesDifficultWhen: 'Income fluctuates wildly month-to-month or unbudgeted emergencies occur without a dedicated reserve.',
    whatChangesOutcome: 'Realistic categorization, review frequency, tracking ease, flexibility for unexpected events, and personal discipline.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'การจัดทำงบประมาณและการวางแผนการเงินส่วนบุคคล',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/money-plan/budgeting.html',
      },
    ],
  },
  {
    elementSlug: 'savings-growth',
    shortDescription: 'The cumulative growth of saved capital over extended time horizons driven by regular contributions and compounding returns.',
    realLesson: 'Savings growth depends on regular contributions, rate of return, time horizon, costs, and inflation, where early consistency amplifies outcomes.',
    example: 'Simplified scenario: Saving THB 3,000 monthly at a nominal 4% annual yield accumulates ~THB 440,000 over 10 years, assuming stable returns and no withdrawals.',
    possibleBenefit: 'Accelerates long-term wealth accumulation and provides financial independence without relying solely on future labor.',
    possibleTradeoff: 'Consistently setting aside savings reduces current discretionary spending capacity over multi-year horizons.',
    hiddenRisk: 'Assuming returns are guaranteed or failing to account for inflation, taxes, and investment fees over time.',
    worksWhen: 'Savings contributions are regular, compounding time horizons are long, and returns exceed cost inflation.',
    becomesDifficultWhen: 'High inflation or low interest rates reduce real yields, or early withdrawals disrupt compounding.',
    whatChangesOutcome: 'Monthly contribution amount, nominal return rate, compounding frequency, time horizon, fees, and inflation rate.',
    realityLevel: RealityLevel.SIMPLIFIED_MODEL,
    safetyLabel: SafetyLabel.SIMULATION_ONLY,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
      {
        title: 'OECD Financial Education Competency Principles',
        organization: 'OECD',
        url: 'https://www.oecd.org/en/topics/financial-education.html',
      },
    ],
  },
  {
    elementSlug: 'debt-trap',
    shortDescription: 'A severe financial cycle where compounding interest costs and high repayment obligations force additional borrowing to cover existing debt.',
    realLesson: 'When debt interest costs exceed monthly repayment capacity, principal balances expand rather than decline, compounding financial strain.',
    example: 'Carrying a THB 100,000 high-interest card debt where paying only minimum monthly charges covers mostly interest, extending debt for years.',
    possibleBenefit: 'Recognizing debt trap dynamics enables early intervention, debt consolidation, or seeking professional debt restructuring.',
    possibleTradeoff: 'Escaping a debt trap requires drastic cuts to non-essential spending and committing all surplus cash flow to principal reduction.',
    hiddenRisk: 'Taking new high-cost informal loans to pay existing formal bank loans rapidly escalates total debt balance into crisis.',
    worksWhen: 'Borrowers prioritize high-interest debt payoff, stop new credit usage, and negotiate structured repayment plans with lenders.',
    becomesDifficultWhen: 'Total monthly debt interest exceeds net monthly surplus cash flow during income interruption.',
    whatChangesOutcome: 'Average interest rate, principal repayment speed, refinancing options, lender negotiation, and spending discipline.',
    realityLevel: RealityLevel.SIMPLIFIED_MODEL,
    safetyLabel: SafetyLabel.NOT_FINANCIAL_ADVICE,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
    ],
  },
  {
    elementSlug: 'purchasing-power-loss',
    shortDescription: 'The gradual reduction in the real volume of goods and services that a fixed sum of cash can buy due to inflation.',
    realLesson: 'Nominal cash balances lose real value over time if yield rates remain below prevailing headline inflation rates.',
    example: 'THB 100,000 kept in a zero-yield cash account during 3% annual inflation loses ~THB 8,500 in real purchasing power over 3 years.',
    possibleBenefit: 'Highlights the necessity of growing capital in inflation-beating assets rather than holding excessive low-yield cash.',
    possibleTradeoff: 'Moving cash into growth assets introduces market price volatility and short-term liquidity trade-offs.',
    hiddenRisk: 'Nominal account balances appear stable, creating a false sense of security while real purchasing power quietly declines.',
    worksWhen: 'Asset allocation strategy balances liquid short-term cash needs with long-term inflation-protected growth assets.',
    becomesDifficultWhen: 'Macroeconomic inflation remains persistently high while safe deposit interest rates stay low.',
    whatChangesOutcome: 'Headline inflation rate, asset yield performance, investment allocation, and holding duration.',
    realityLevel: RealityLevel.SIMPLIFIED_MODEL,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
      {
        title: 'OECD Financial Education Competency Principles',
        organization: 'OECD',
        url: 'https://www.oecd.org/en/topics/financial-education.html',
      },
    ],
  },
  {
    elementSlug: 'lifestyle-creep',
    shortDescription: 'The tendency for discretionary spending and baseline living standards to expand automatically whenever income increases.',
    realLesson: 'Lifestyle creep consumes earned income raises, preventing higher earnings from translating into increased savings rates or wealth growth.',
    example: 'Receiving a THB 10,000 monthly salary raise and immediately upgrading housing and vehicle leases, keeping monthly savings unchanged.',
    possibleBenefit: 'Upgrading lifestyle comforts can reward hard work and improve daily well-being within intentional limits.',
    possibleTradeoff: 'Automatically spending income raises locks households into higher fixed expenses, increasing future baseline financial needs.',
    hiddenRisk: 'Inflated lifestyle expectations become difficult to downgrade if income subsequently declines or experiences a shock.',
    worksWhen: 'Households enforce a "save first" rule on salary raises (e.g. allocating 50%+ of any raise directly to savings or debt payoff).',
    becomesDifficultWhen: 'Social comparison, peer expectations, or status purchasing drive automatic spending increases with every raise.',
    whatChangesOutcome: 'Save-first discipline on raises, awareness of fixed vs variable cost expansion, and clear long-term goals.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'แยกให้ปัง... Needs กับ Wants วางแผนเงินอย่างไรไม่ให้รั่วไหล',
        organization: 'Stock Exchange of Thailand',
        url: 'https://www.setinvestnow.com/th/knowledge/article/117-needs-vs-wants',
      },
    ],
  },
  {
    elementSlug: 'emergency-liquidity',
    shortDescription: 'The specific portion of emergency reserves held in immediately accessible, principal-protected liquid instruments.',
    realLesson: 'Immediate liquidity ensures cash is accessible within hours without penalty or market loss during an urgent financial crisis.',
    example: 'Keeping THB 30,000 in an instant-transfer high-yield savings account to handle immediate car repairs or medical co-pays.',
    possibleBenefit: 'Guarantees instant access to funds when needed without relying on high-interest credit cards or selling assets at a loss.',
    possibleTradeoff: 'Highly liquid deposit accounts offer lower interest yields compared to locked term deposits or investment funds.',
    hiddenRisk: 'Keeping emergency liquidity in everyday checking accounts increases temptation for non-emergency discretionary spending.',
    worksWhen: 'Liquid funds are stored in separate, penalty-free deposit accounts with instant transfer capability.',
    becomesDifficultWhen: 'Urgent liquidity needs exceed immediate account balances during banking holidays or system outages.',
    whatChangesOutcome: 'Account access speed, withdrawal penalty terms, separation from daily spending accounts, and deposit protection.',
    realityLevel: RealityLevel.GROUNDED,
    safetyLabel: SafetyLabel.EDUCATION_ONLY,
    sources: [
      {
        title: 'สื่อการสอนความรู้ทางการเงินตามกรอบสมรรถนะทางการเงินเพื่อการศึกษาและการเรียนรู้',
        organization: 'Bank of Thailand',
        url: 'https://www.bot.or.th/th/satang-story/satang-school/BOT-teaching-tools.html',
      },
      {
        title: 'สถาบันคุ้มครองเงินฝาก (Deposit Protection Agency Thailand)',
        organization: 'Deposit Protection Agency Thailand',
        url: 'https://www.dpa.or.th',
      },
    ],
  },
];
