import {
  ContentStatus,
  ElementType,
} from '../../../src/database/generated/prisma/client';

export interface ElementSeedInput {
  slug: string;
  name: string;
  categoryName: string;
  elementType: ElementType;
  emoji: string;
  isStarter: boolean;
  status: ContentStatus;
  sortOrder: number;
}

export const STARTER_ELEMENT_SEED_DATA: ElementSeedInput[] = [
  {
    slug: 'income',
    name: 'Earned Income',
    categoryName: 'Money Flow',
    elementType: ElementType.BASE,
    emoji: '💵',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 1,
  },
  {
    slug: 'expense',
    name: 'General Expense',
    categoryName: 'Cost of Living',
    elementType: ElementType.BASE,
    emoji: '💳',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 2,
  },
  {
    slug: 'saving',
    name: 'Basic Savings',
    categoryName: 'Saving & Financial Safety',
    elementType: ElementType.BASE,
    emoji: '🏦',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 3,
  },
  {
    slug: 'debt',
    name: 'Borrowed Debt',
    categoryName: 'Debt & Credit',
    elementType: ElementType.BASE,
    emoji: '📝',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 4,
  },
  {
    slug: 'interest',
    name: 'Interest Rate',
    categoryName: 'Debt & Credit',
    elementType: ElementType.TOOL,
    emoji: '📈',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 5,
  },
  {
    slug: 'inflation',
    name: 'Market Inflation',
    categoryName: 'Cost of Living',
    elementType: ElementType.RISK,
    emoji: '🎈',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 6,
  },
  {
    slug: 'emergency-fund',
    name: 'Emergency Fund',
    categoryName: 'Saving & Financial Safety',
    elementType: ElementType.TOOL,
    emoji: '🛡️',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 7,
  },
  {
    slug: 'food',
    name: 'Food & Groceries',
    categoryName: 'Cost of Living',
    elementType: ElementType.BASE,
    emoji: '🍲',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 8,
  },
  {
    slug: 'rent',
    name: 'Shelter Rent',
    categoryName: 'Cost of Living',
    elementType: ElementType.BASE,
    emoji: '🏠',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 9,
  },
  {
    slug: 'budget',
    name: 'Budget Plan',
    categoryName: 'Planning Tools',
    elementType: ElementType.TOOL,
    emoji: '📊',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 10,
  },
  {
    slug: 'needs',
    name: 'Essential Needs',
    categoryName: 'Cost of Living',
    elementType: ElementType.CONCEPT,
    emoji: '🧱',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 11,
  },
  {
    slug: 'wants',
    name: 'Discretionary Wants',
    categoryName: 'Financial Behavior',
    elementType: ElementType.CONCEPT,
    emoji: '🎁',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 12,
  },
  {
    slug: 'fomo',
    name: 'Social Pressure / FOMO',
    categoryName: 'Financial Behavior',
    elementType: ElementType.RISK,
    emoji: '📱',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 13,
  },
  {
    slug: 'job-loss',
    name: 'Unexpected Job Loss',
    categoryName: 'Life Events & Risk',
    elementType: ElementType.RISK,
    emoji: '⚡',
    isStarter: true,
    status: ContentStatus.ACTIVE,
    sortOrder: 14,
  },
];
